FEgor04/itmo-is-1

.github/workflows/ci.yaml

ci: run checks for PR

---

backend/src/main/kotlin/com/jellyone/lab1/controller/CarController.kt
backend/src/main/kotlin/com/jellyone/lab1/controller/HumanBeingController.kt
backend/src/main/kotlin/com/jellyone/lab1/dto/CarDto.kt
backend/src/main/kotlin/com/jellyone/lab1/mapper/CarMapper.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/CarRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/PaginatedResponse.kt
backend/src/main/kotlin/com/jellyone/lab1/service/CarService.kt

feat: pagination, filters and sort for GET /cars

---

frontend/src/shared/ui/pagination.tsx

fix: totalPages computation

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/app/routes/__root.tsx
frontend/src/app/routes/cars.tsx
frontend/src/app/routes/signin.tsx
frontend/src/entities/principal/api.ts
frontend/src/entities/principal/profile.tsx
frontend/src/shared/api.gen.ts
frontend/src/shared/ui/sheet.tsx
frontend/src/shared/ui/skeleton.tsx
frontend/src/shared/ui/tooltip.tsx

feat: add sidebar menu

---

frontend/src/app/routes/__root.tsx
frontend/src/app/routes/cars.tsx
frontend/src/app/routes/humans/route.tsx
frontend/src/entities/car/api.ts
frontend/src/entities/car/create.tsx
frontend/src/entities/car/edit.tsx
frontend/src/entities/car/model.ts
frontend/src/entities/car/table.tsx

feat: cars page

---

backend/src/main/kotlin/com/jellyone/lab1/controller/HumanBeingController.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/HumanBeingRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/service/HumanBeingService.kt
frontend/src/app/routes/__root.tsx
frontend/src/app/routes/_auth/humans.tsx
frontend/src/entities/human-being/api.ts
frontend/src/shared/api.gen.ts

feat: add filter by impact speed

---

.github/workflows/cd.yaml
ansible/ansible.cfg
ansible/env.j2
ansible/helios.yaml
ansible/inventory/inventory.ini
ansible/inventory/prod.ini
ansible/staging.yaml

cd: use ansible to deploy on staging

---

Makefile
frontend/src/app/App.tsx

fix: refetch on focus via custom focusManager

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/controller/CarController.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/CarRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/service/CarService.kt
frontend/src/app/routes/_auth/cars.tsx
frontend/src/app/routes/_auth/humans.tsx
frontend/src/entities/car/api.ts
frontend/src/shared/api.gen.ts
frontend/src/shared/ui/controls.tsx
frontend/src/shared/ui/pagination.tsx

feat(cars): add filter by color

---

.github/workflows/release.yml
Makefile

cd: fix release deploy

---

.github/workflows/release.yml
Makefile

deploy: fix version variable

---

ansible/helios.yaml

fix: append to log file

---

Makefile
frontend/src/app/routes/index.tsx

feat: show another CTA if not authed

---

Makefile
backend/src/test/kotlin/com/jellyone/lab1/controller/AuthControllerTest.kt

test(backend): coverage of AuthController

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/controller/UserController.kt
backend/src/main/kotlin/com/jellyone/lab1/domain/User.kt
backend/src/main/kotlin/com/jellyone/lab1/web/security/JwtTokenFilter.kt
backend/src/main/kotlin/com/jellyone/lab1/web/security/JwtTokenProvider.kt
backend/src/test/kotlin/com/jellyone/lab1/controller/AdminControllerTest.kt
backend/src/test/kotlin/com/jellyone/lab1/controller/AuthControllerTest.kt

fix(backend): get user role from jwt

---

Makefile
backend/src/test/kotlin/com/jellyone/lab1/controller/CarControllerTest.kt
backend/src/test/kotlin/com/jellyone/lab1/controller/UserControllerTest.kt

test(backend):  coverage of CarController

---

.github/workflows/release.yml
ansible/helios.yaml
ansible/start.j2
ansible/stop.j2

deploy: add scripts for manual deployment

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/controller/AuthController.kt
frontend/src/app/routes/_auth/visualize.tsx
frontend/src/entities/human-being/ui/visualization.tsx
frontend/src/shared/api.gen.ts
frontend/src/shared/auth.ts

при рефреше токена использовалась неверная ручка
заменить ручку на метод, сгенерированный с помощью `swagger`. Также нужно форсированно указать `Content-Type: text/plain`

fix: refresh token on frontend

---

Makefile
frontend/src/app/routes/__root.tsx

fix(frontend): remove devtools from prod build

---

Makefile
frontend/src/entities/car/select.tsx
frontend/src/entities/human-being/ui/edit.tsx
frontend/src/entities/human-being/ui/visualization.tsx

fix: disable edit for other users' humanBeings in visualization

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/repository/AdminRequestRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/CarRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/HumanBeingRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/LogsRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/UserRepository.kt

fix(backend): add @Transactional

---

Makefile
frontend/index.html

fix(frontend): set title

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/repository/HumanBeingRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/service/ImportService.kt

feat(ImportService): add saveAll method

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/service/ImportService.kt

Add validator inner class

---

scripts/auth-users.sh
scripts/create-users.sh

feat(jmeter-harness): auth scripts

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/service/HumanBeingService.kt
backend/src/main/kotlin/com/jellyone/lab1/service/ImportService.kt

fix(ImportService): change checkNameIsNotUnique method

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/service/HumanBeingService.kt
backend/src/main/kotlin/com/jellyone/lab1/service/ImportService.kt

fix(ImportService): change ResourceAlreadyExistsException message

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/service/CarService.kt
backend/src/main/kotlin/com/jellyone/lab1/service/HumanBeingService.kt
backend/src/main/kotlin/com/jellyone/lab1/service/ImportService.kt
backend/src/main/kotlin/com/jellyone/lab1/service/impl/AuthServiceImpl.kt
backend/src/main/kotlin/com/jellyone/lab1/service/impl/LogsServiceImpl.kt
backend/src/main/kotlin/com/jellyone/lab1/service/impl/UserServiceImpl.kt

feat(backend): add `Transactional` annotations

---

Makefile
frontend/src/shared/ui/pagination.tsx

fix: add total pages to pagination

---

.github/workflows/cd.yaml
.github/workflows/release.yml

cd: add GitHub deployments concurrency

---

Makefile
backend/build.gradle.kts
backend/src/main/kotlin/com/jellyone/lab1/repository/HumanBeingRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/ImportRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/service/HumanBeingService.kt
backend/src/test/kotlin/Lab1Simulation.kt

feat: add Gatling gun, fix transactions isolation

---

Makefile
backend/src/main/kotlin/com/jellyone/lab1/controller/ImportController.kt
backend/src/main/kotlin/com/jellyone/lab1/repository/ImportRepository.kt
backend/src/main/kotlin/com/jellyone/lab1/service/FileService.kt
backend/src/main/kotlin/com/jellyone/lab1/service/ImportService.kt
backend/src/test/kotlin/ImportDataSimulation.kt
backend/src/test/kotlin/Lab1Simulation.kt

feat(backend): check permissions for get file, refactoring code
